[2025-06-29T12:38:54.954+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl manual__2025-06-29T12:38:54+00:00 [queued]>
[2025-06-29T12:38:54.960+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl manual__2025-06-29T12:38:54+00:00 [queued]>
[2025-06-29T12:38:54.961+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-29T12:38:55.048+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_batch_youtube_etl> on 2025-06-29 12:38:54+00:00
[2025-06-29T12:38:55.051+0000] {standard_task_runner.py:60} INFO - Started process 250 to run task
[2025-06-29T12:38:55.052+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_kpi_daily_batch', 'run_batch_youtube_etl', 'manual__2025-06-29T12:38:54+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/youtube_etl_dag.py', '--cfg-path', '/tmp/tmp77yzx11t']
[2025-06-29T12:38:55.053+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask run_batch_youtube_etl
[2025-06-29T12:38:55.061+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-29T12:38:55.076+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl manual__2025-06-29T12:38:54+00:00 [running]> on host d0ff4814d978
[2025-06-29T12:38:55.111+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yonatan' AIRFLOW_CTX_DAG_ID='youtube_kpi_daily_batch' AIRFLOW_CTX_TASK_ID='run_batch_youtube_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-06-29T12:38:54+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-29T12:38:54+00:00'
[2025-06-29T12:38:55.122+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UCvtRTOMP2TqYqu51xNrqAzg
[2025-06-29T12:38:55.366+0000] {logging_mixin.py:188} INFO - Failed for UCvtRTOMP2TqYqu51xNrqAzg: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 3:         FROM youtube_kpi.youtube_channel_stats
                     ^
[2025-06-29T12:38:55.367+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UC0ZV6M2THA81QT9hrVWJG3A
[2025-06-29T12:38:55.584+0000] {logging_mixin.py:188} INFO - Failed for UC0ZV6M2THA81QT9hrVWJG3A: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 3:         FROM youtube_kpi.youtube_channel_stats
                     ^
[2025-06-29T12:38:55.585+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UCYzPXprvl5Y-Sf0g4vX-m6g
[2025-06-29T12:38:55.792+0000] {logging_mixin.py:188} INFO - Failed for UCYzPXprvl5Y-Sf0g4vX-m6g: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 3:         FROM youtube_kpi.youtube_channel_stats
                     ^
[2025-06-29T12:38:55.793+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UCbg_UMjlHJg_19SZckaKajg
[2025-06-29T12:38:55.992+0000] {logging_mixin.py:188} INFO - Failed for UCbg_UMjlHJg_19SZckaKajg: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 3:         FROM youtube_kpi.youtube_channel_stats
                     ^
[2025-06-29T12:38:55.992+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UCDVPcEbVLQgLZX0Rt6jo34A
[2025-06-29T12:38:56.212+0000] {logging_mixin.py:188} INFO - Failed for UCDVPcEbVLQgLZX0Rt6jo34A: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 3:         FROM youtube_kpi.youtube_channel_stats
                     ^
[2025-06-29T12:38:56.213+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UC5zJwsFtEs9WYe3A76p7xIA
[2025-06-29T12:38:56.402+0000] {logging_mixin.py:188} INFO - Failed for UC5zJwsFtEs9WYe3A76p7xIA: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 3:         FROM youtube_kpi.youtube_channel_stats
                     ^
[2025-06-29T12:38:56.403+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UCDSJCBYqL7VQrlXfhr1RtwA
[2025-06-29T12:38:56.610+0000] {logging_mixin.py:188} INFO - Failed for UCDSJCBYqL7VQrlXfhr1RtwA: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 3:         FROM youtube_kpi.youtube_channel_stats
                     ^
[2025-06-29T12:38:56.611+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UC2C_jShtL725hvbm1arSV9w
[2025-06-29T12:38:56.829+0000] {logging_mixin.py:188} INFO - Failed for UC2C_jShtL725hvbm1arSV9w: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 3:         FROM youtube_kpi.youtube_channel_stats
                     ^
[2025-06-29T12:38:56.830+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UCZDdF_p-L88NWVpzF0vjvMQ
[2025-06-29T12:38:57.035+0000] {logging_mixin.py:188} INFO - Failed for UCZDdF_p-L88NWVpzF0vjvMQ: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 3:         FROM youtube_kpi.youtube_channel_stats
                     ^
[2025-06-29T12:38:57.035+0000] {logging_mixin.py:188} INFO - Running ETL for channel: UC648rgJOboZlgcDbW00vTSA
[2025-06-29T12:38:57.237+0000] {logging_mixin.py:188} INFO - Failed for UC648rgJOboZlgcDbW00vTSA: relation "youtube_kpi.youtube_channel_stats" does not exist
LINE 3:         FROM youtube_kpi.youtube_channel_stats
                     ^
[2025-06-29T12:38:57.238+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-29T12:38:57.253+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=youtube_kpi_daily_batch, task_id=run_batch_youtube_etl, execution_date=20250629T123854, start_date=20250629T123854, end_date=20250629T123857
[2025-06-29T12:38:57.279+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-29T12:38:57.294+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
