[2025-06-30T11:11:42.938+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl manual__2025-06-30T11:06:07.366314+00:00 [queued]>
[2025-06-30T11:11:42.944+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl manual__2025-06-30T11:06:07.366314+00:00 [queued]>
[2025-06-30T11:11:42.945+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-30T11:11:43.101+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_batch_youtube_etl> on 2025-06-30 11:06:07.366314+00:00
[2025-06-30T11:11:43.106+0000] {standard_task_runner.py:60} INFO - Started process 605 to run task
[2025-06-30T11:11:43.110+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_kpi_daily_batch', 'run_batch_youtube_etl', 'manual__2025-06-30T11:06:07.366314+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/youtube_etl_dag.py', '--cfg-path', '/tmp/tmpyzylxgzo']
[2025-06-30T11:11:43.114+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask run_batch_youtube_etl
[2025-06-30T11:11:43.125+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-30T11:11:43.149+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_kpi_daily_batch.run_batch_youtube_etl manual__2025-06-30T11:06:07.366314+00:00 [running]> on host f52b64ea71aa
[2025-06-30T11:11:43.197+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yonatan' AIRFLOW_CTX_DAG_ID='youtube_kpi_daily_batch' AIRFLOW_CTX_TASK_ID='run_batch_youtube_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T11:06:07.366314+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T11:06:07.366314+00:00'
[2025-06-30T11:11:43.221+0000] {logging_mixin.py:188} INFO - Processing channels 1 to 50...
[2025-06-30T11:11:43.783+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/batch_etl.py", line 23, in batch_run
    vid = extract_latest_video_id(ch["channel_id"])
  File "/opt/airflow/scripts/extract_youtube_data.py", line 145, in extract_latest_video_id
    search_response.raise_for_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/youtube/v3/search?key=AIzaSyAFiKSpDVcYBOkCe_3ts37XM3VE3DIduQ0&channelId=UCYzPXprvl5Y-Sf0g4vX-m6g&part=snippet&order=date&maxResults=1&type=video
[2025-06-30T11:11:43.793+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=youtube_kpi_daily_batch, task_id=run_batch_youtube_etl, execution_date=20250630T110607, start_date=20250630T111142, end_date=20250630T111143
[2025-06-30T11:11:43.801+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 21 for task run_batch_youtube_etl (403 Client Error: Forbidden for url: https://www.googleapis.com/youtube/v3/search?key=AIzaSyAFiKSpDVcYBOkCe_3ts37XM3VE3DIduQ0&channelId=UCYzPXprvl5Y-Sf0g4vX-m6g&part=snippet&order=date&maxResults=1&type=video; 605)
[2025-06-30T11:11:43.850+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-30T11:11:43.866+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
